### ISSUE TITLE
Symlinks not created when packing.

### ISSUE THREAD

**Issue by valqk** [quazardous/silex-pack#1]
https://github.com/quazardous/silex-pack/blob/master/src/Silex/PackableApplication.php#L330
I think you have added one extra ! before is_file()...
If I remove it I get links properly created.
I might be wrong, and that's why created an issue instead of forking+fixing.

Thanks for the nice app!
Saved me 1 more week struggling around!

**Comment by quazardous** [comment]
hi,

my guess is that it does create links but on non existing files...

say your pack is `/path/to/MyPack.php`:

```
[
//source => dest,

// will create a symlink web/folder1 to /path/to/folder1
'folder1' => 'folder1',

// will create a symlink web/folderX to /another/path/to/folder2
'/another/path/to/folder2' => 'folderX',

// will create a symlink /foo/folderX to /another/path/to/folder2
'/another/path/to/folder2' => '/foo/folderX',
]

```

maybe I should have use dest => source

**Comment by valqk** [comment]
Hmm... 
it's
`if (!is_file($source)) continue;`
usually source is directory, and it's skipped, instead of linking it to $dest...
or I'm missing something?

**Comment by quazardous** [comment]
omg I always thought `is_file()` was like `file_exists()`

http://stackoverflow.com/questions/792899/is-file-or-file-exists-in-php

Can you create a PR with `file_exists()` ?
