### ISSUE TITLE
ClassNotFoundException : Attempted to load class "ConsoleEvents" from namespace "Quazardous\Silex\Console"

### ISSUE THREAD

**Issue by radonthetyrant** [quazardous/silex-pack#3]
```
ClassNotFoundException in PackableApplication.php line 215:
Attempted to load class "ConsoleEvents" from namespace "Quazardous\Silex\Console".
Did you forget a "use" statement for "Symfony\Component\Console\ConsoleEvents"?
in PackableApplication.php line 215
at PackableApplication->registerConsolablePack(object(RotkrautCorePack)) in PackableApplication.php line 40
at PackableApplication->boot() in Application.php line 491
at Application->handle(object(Request)) in Application.php line 477
at Application->run() in index_dev.php line 22
```
File has 2 use statements for both ConsoleEvent and ConsoleEvents in L13-14:
```
use Quazardous\Silex\Console\ConsoleEvents;
use Quazardous\Silex\Console\ConsoleEvent;
```
But they don't seem to exist. And changing those to:
```
use Symfony\Component\Console\ConsoleEvents;
use Symfony\Component\Console\Event\ConsoleEvent;
```
fails, because the symfony ones don't have the same signature.

**Comment by radonthetyrant** [comment]
ok, apparently your project depends on silex-console which is not set as a depencency in composer.json

**Comment by quazardous** [comment]
hi, yes it's not in the dependencies because you can choose not to implement consolable interface... it's suggested.... (and needed if you use the all in one jetpack interface).

you can use the dependencies of https://github.com/quazardous/silex-pack-demo as guide...

**Comment by radonthetyrant** [comment]
Thanks, just wanted to let you know since it looks like an easy bug to stumble into when you just include the silex-pack and try to use the JetPackInterface. Maybe duplicating the classes into both packages could help? Just a suggestion.

Thanks,
